### PR TITLE
149 filter for charging history

### PR DESCRIPTION
**Pull request by flrn579**
# Pull Request
## Issue number
#149

## Task list 
- [x] Checked the code structure so it follows guide lines
- [x] Checked that all the points in the Issue are solved
- [x] Checked that all the old tests still got approved

## Added tests
- [ ] Yes, I have added tests
- [x] No, I have not added tests
- [ ] No, I need help with adding tests

### CODE REVIEW

**Comment by GabrielAdward** [comment]
Right now the sidebar does not match with the image provided below.
Current:
image

Image to follow:
image

**Review by GabrielAdward — CHANGES_REQUESTED** [review]
Right now the sidebar does not match with the image provided below.
Current:
image

Image to follow:
image

**Comment by flrn579** [comment]
Yes, that is because it is part of another issue and thus in an other branch

**Review by GabrielAdward — CHANGES_REQUESTED** [review]
Could you add mock data and see if you switch pages when you choose 25 rows to be displayed on the charging history?

**Review by GabrielAdward — APPROVED** [review]
LGTM!

**Review by HeWhoThreadsLightly — COMMENTED** [review]
Code looks good to me, could use some comments for next year but nothing critical.

Manual testing sorting the colums by each value work.
Has a minor graphical issue where the colum width change when sorting based on location depending on location name length. This makes the columns change location slightly.

Could use a test that checks if the sorthing works but I wont insist on it.

**Pull request merged**
